package bawei.com.greedaotest.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bawei.com.zdw_greendao_test.ZdwWork;

import bawei.com.greedaotest.dao.ZdwWorkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zdwWorkDaoConfig;

    private final ZdwWorkDao zdwWorkDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zdwWorkDaoConfig = daoConfigMap.get(ZdwWorkDao.class).clone();
        zdwWorkDaoConfig.initIdentityScope(type);

        zdwWorkDao = new ZdwWorkDao(zdwWorkDaoConfig, this);

        registerDao(ZdwWork.class, zdwWorkDao);
    }
    
    public void clear() {
        zdwWorkDaoConfig.clearIdentityScope();
    }

    public ZdwWorkDao getZdwWorkDao() {
        return zdwWorkDao;
    }

}
